### ISSUE TITLE
Correct links

### ISSUE THREAD

**Issue by remcoploeg** [Microsoft/mvp-summit-iot-workshop#15]
"links" : [
    {"source" : "*", "sink" : "Logger" },
    {"source" : "SensorTag", "sink" : "mapping" },
    {"source" : "SensorTag", "sink" : "BLE Printer" },
    {"source" : "mapping", "sink" : "IoTHub" },
    {"source" : "IoTHub", "sink" : "mapping" },
    {"source" : "mapping", "sink" : "BLEC2D" },
    {"source" : "BLEC2D", "sink" : "SensorTag"}
  ]

**Comment by chipalost** [comment]
Thanks, that's been fixed now.
