### ISSUE TITLE
Routing configuration needs an extra link

### ISSUE THREAD

**Issue by ppolyzos** [Microsoft/mvp-summit-iot-workshop#16]
I found out that in order for the iot-gateway demo to work, you need one more routing configuration entry,
* The **mapping** module sends messages to the **BLE2CD** module and
* the **BLE2CD** module sends messages back to the **SensorTag** module. 

The links section should be like this:
```
"links" : [
    {"source" : "*", "sink" : "Logger" },
    {"source" : "SensorTag", "sink" : "mapping" },
    {"source" : "SensorTag", "sink" : "BLE Printer" },
    {"source" : "mapping", "sink" : "IoTHub" },
    {"source" : "IoTHub", "sink" : "mapping" },
    {"source" : "mapping", "sink" : "BLEC2D" },
    {"source" : "BLEC2D", "sink": "SensorTag" }
  ]
```

**Comment by chipalost** [comment]
Thanks, I've fixed this.
